== Predeployment steps

=== Confirm your AMC instance

To confirm that you have an AMC instance provisioned and active, go to https://advertising.amazon.com/register?ref_=a20m_us_hnav_rgstr[Register for Amazon Ads^], and choose *switch to your advertising account*.

=== Set up your environment

You need to set up an environment with programmatic access to your AWS account and with various tools at appropriate versions. You can set up your environment locally or in AWS Cloud9, as detailed in the following sections.

==== Set up a local environment

. Confirm that your local environment has Python version 3.7 or later and its package manager, pip, version 9.0.3 or later.
+
```
$ python --version
$ pip --version
```

. Confirm that the AWS Command Line Interface (AWS CLI) is installed and configured.
+
```
$ aws --version
```

. Confirm that you have AWS CDK version 2.10 or later.
+
```
$ cdk --version
```

. Confirm that Git is installed and configured.
+
```
$ git --version
```

. If this is your first time using Git, set your user name and email address as follows, replacing the information in brackets.
+
```
$ git config --global user.name <YOUR NAME>
$ git config --global user.email <YOU@EMAIL.COM>
```

. Confirm that Git is configured.
+
```
$ git config --list
```

==== Set up an AWS Cloud9 environment

. Sign in to the AWS Management Console using the *Admin* role, and choose an AWS Region. Choose a mature Region where most services are available, such as eu-west-1 or us-east-1.

. Open the AWS Cloud9 console, and create an EC2 environment in your chosen AWS Region. Choose instance type t3.small or larger, Amazon Linux 2. For details refer to https://docs.aws.amazon.com/cloud9/latest/user-guide/create-environment-main.html[Creating an EC2 Environment^].

. In your integrated development environment (IDE), download the https://fwd.aws/Rp8mK?[{partner-product-name} repository^], upload it to your AWS Cloud9 instance, and unzip it.
+
By default, Python, pip, AWS CLI, AWS CDK, and Git are installed and configured for you in your AWS Cloud9 environment.

. Confirm that the packages are all installed by entering the following commands:
+
```
$ python --version
$ pip --version
$ aws --version
$ cdk --version
$ git --version
```

. Verify the following versions:
* Python 3.7 or later.
* pip 9.0.3 or later.
* AWS CDK version 2.10 or later.

=== Clone the repo

Clone the https://fwd.aws/Rp8mK?[{partner-product-name} repository^] as follows, replacing the information in brackets.

```
$ git clone <GITHUB-PATH>
$ cd quickstart-amazon-marketing-cloud
$ rm -rf .git

```

=== Install and set up the DDK

. Install the DataOps Development Kit.
+
```
$ pip install aws-ddk
```

. Verify the installation.
+
```
$ ddk --help
```

. Create and activate a virtual environment.
+
```
$ python -m venv .venv && source .venv/bin/activate
```

. Install the application's dependencies.
+
```
$ pip install -r requirements.txt --no-cache-dir
```
+
The https://pypi.org/project/aws-ddk-core/[DataOps Development Kit (DDK) Core^], a library of AWS CDK constructs, is installed.

. If your AWS account hasn't been used to deploy DDK apps before, bootstrap your environment as follows, replacing the information in brackets. .
+
```
$ ddk bootstrap --help
$ ddk bootstrap --profile <AWS_PROFILE> --trusted-accounts <AWS_ACCOUNT_ID>
```
+
You might recognize a number of files typically found in an AWS CDK Python application, such as `app.py` and `cdk.json`. In addition, `ddk.json` holds configuration information about DDK constructs.

. Edit the required parameters in `ddk.json`. Enter your account ID, the name of the AWS CodeCommit repository to reference (you'll create this repository in a later step), and names of data lake parameters such as `app`, `org`, `team`, `dataset`, and `pipeline`.
+
```
$ vi ddk.json
```

. Initialize Git for the repository.
+

```
$ git init --initial-branch main
```

. Create a new CodeCommit repository as follows. Replace the information in brackets, using the repository name value from the `ddk.json` configuration file. The template is launched in the {default_deployment_region} Region by default; change this Region if necessary in the following command.
+
```
$ ddk create-repository <AMC_REPO_NAME> --profile <AWS_PROFILE> --region <AWS_REGION>
```

. Add and push the initial commit to the repository as follows, replacing the information in brackets.
+

```
$ git config --global credential.helper "!aws codecommit --profile <my-profile> credential-helper $@"
$ git config --global credential.UseHttpPath true
$ git add .
$ git commit -m "Configure AMC Insights on AWS"
$ git push --set-upstream origin main
```

== Deployment steps

Deploying this solution takes about {deployment_time} to complete.

. Run the `deploy` command as follows, replacing the information in brackets.
+
```
$ ddk deploy --profile <AWS_PROFILE>
```

. If the status is FAILED in the assets stage of deploying AWS CodePipeline (due to the limited number of file assets that AWS CodeBuild can publish concurrently), choose the *Retry* button. This prompts CodePipeline to continue building the file assets.